### ISSUE TITLE
החיפוש באי ירוק 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#1]

**Comment by shirachen** [comment]
ולוודא שגם זה תקין
היי עמר,
עוד תיקון קטן 

שמנו לב שתיקון המילים לחיפוש באתר לא באמת עובד. תיקנו כל מיני מילים (כינרת-כנרת, אופנים=אופניים, בירייה=ביריה וכו') אבל החיפוש לא מוצא אותן.
למשל:
![image](https://cloud.githubusercontent.com/assets/14195653/10456842/074555b6-71cc-11e5-93dc-1bc6562a2cc4.png)

![image](https://cloud.githubusercontent.com/assets/14195653/10456856/150e2a38-71cc-11e5-9bbf-50c928884172.png)

![image](https://cloud.githubusercontent.com/assets/14195653/10456866/1f35ad92-71cc-11e5-8d0a-a9b0405992c7.png)

**Comment by naticomstar** [comment]
מבדיקה במערכת המקומית הנ"ל עובד, התיקון יעלה יחד עם הגלילה האינסופית, יש לבדוק מחדש באתר לאחר ההעלאה.
