### ISSUE TITLE
מנגנון החיפוש 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#10]
![image](https://cloud.githubusercontent.com/assets/14195653/10634375/0e29e2d2-77fa-11e5-8710-d8cf5292aa4c.png)

**Comment by naticomstar** [comment]
דרש חצי שעת פיתוח- יתווסף למשימה כוללת
(שם מחזור: אי ירוק קק"ל- שינויים ותיקונים קטנים באי ירוק 21/10/2015)

**Comment by kazantip151** [comment]
היי , המסלול אופניים עדיין נפתח באותו חלון.

**Comment by gadcomstar** [comment]
טופל ויעלה כחלק מהעלאה המרוכזת

**Comment by naticomstar** [comment]
בוצע
