### ISSUE TITLE
מנגנון החיפוש 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#11]
עשיתי פעם אחת וזה עבד 
עכשיו מנסה חיפוש אחר וזה מוביל אותי לעמוד שגיאה 47

**Comment by shirachen** [comment]
גם ניקיתי קאש וגם ניסיתי באינקוניטו
וגןם במחשב אחר

ניסיתי לכתוב אשתאול

**Comment by naticomstar** [comment]
סודר. נקי קאש שוב ותנסי כעת
