### ISSUE TITLE
 בדף הבית - שינוי כותרות ואלט

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#14]
ככה
![image](https://cloud.githubusercontent.com/assets/14195653/10726435/608483e0-7bdb-11e5-8664-8ff2be0cfc58.png)

**Comment by naticomstar** [comment]
לא ברור מה הבעיה של הALTים

**Comment by shirachen** [comment]
בבקשה הוסף אלט לתמונה מרכזית

**Comment by naticomstar** [comment]
עודכן

**Comment by shirachen** [comment]
גם כל הכותרות שוני לפי ה h השונים?

**Comment by naticomstar** [comment]
תבדקי ותראי שכן

**Comment by shirachen** [comment]
- ״החמישיה הפותחת״ = עדיין h1, 
  הוא צריך להיות h2. 
- שימו לב! - שצריך לעשות את אותם שינויים של הכותרות גם בגרסת המובייל של האתר (זה מופיע בקוד הרגיל).

**Comment by naticomstar** [comment]
שימי לב שסימנת בתמונה שלך את "חמישה טיולי אופניים בצפון" ולא את "החמישייה הפותחת" ולכן עודכן רק מה שביקשת

**Comment by shirachen** [comment]
במובייל זה טופל?

**Comment by naticomstar** [comment]
אכן

**Comment by shirachen** [comment]
בבקשה שגם החמישי ה הפותחת יהיה 
h2

**Comment by naticomstar** [comment]
עודכן. כל הנ"ל יחוייב בחצי שעת עבודה במשימה מרכזת
