### ISSUE TITLE
קנוקניקל

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#15]
גלינו חוסר תאימות בין הנלינק שנחשב הקנוניקל לבין הלינק שמפנה אליו
למשל:
http://www.eyarok.org.il/PathOnMap.aspx?id=2027
![image](https://cloud.githubusercontent.com/assets/14195653/10727029/69fffc7a-7bdf-11e5-9d08-f3a2ab02d4c1.png)

אבל הקנוניקל של התמונה מוגדר ללא אותיות גדולות 
למשל:
http://www.eyarok.org.il/pathonmap.aspx?id=2027

![image](https://cloud.githubusercontent.com/assets/14195653/10727059/a3f95638-7bdf-11e5-85a9-d391ec1d1066.png)

**Comment by gadcomstar** [comment]
הנושא טופל. מעתה והלאה כל הכתובות יהיו באותיות קטנות (עם הפנייה 301).
