### ISSUE TITLE
שכפול טקסטים באי הילדים

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#16]
בהקמת אי הילדים סוכם כי כל מסלול שאין לו תוכן ייחודי עבור אי הילדים יישאב אוטומטית מהעמוד טיול המקביל לו באי ירוק
אנחנו רוצים להתסיר זאת מגוגל עקב הערות seo
ולכן נרצה לעדכן חסימת עמודים (המשוכפלים בלבד) אלו מגוגל בעזרת 
no index 

שימו לב שאתם מכילים את זה על הקנוניקל של אותו עמוד

לפני ביצוע משימה זו יש לקבל ממני אישור במייל
תודה שירה

**Comment by shirachen** [comment]
מאושר לביצוע - אין צורך לשלוח לי מייל לפני

**Comment by naticomstar** [comment]
ידרוש שעת עבודה, נא אישורכם

**Comment by shirachen** [comment]
מאושר

**Comment by naticomstar** [comment]
בוצע, תקף גם לעמוד מסלול וגם לעמודי כתבות מגזין (מופרד בעמודים, מתנהג זהה)
