### ISSUE TITLE
קישורים מאי הילדים לאופניים

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#17]
גילינו שמסלולים ישנים וחדשים שעלו באתר האופניים למשל
עמודי אב 
ועמודי מסלול רגילים 
נשאבים לאי הילדים
ומקבלים לינק משובש ולא קיים לדוגמה
http://www.eyarok.org.il/KidsIsland/bike/trip.aspx?id=1967
http://www.eyarok.org.il/KidsIsland/bike/bike/maintrip.aspx?id=1

![image](https://cloud.githubusercontent.com/assets/14195653/10727482/eaa53ed2-7be2-11e5-943f-6f47bb3a930b.png)

![image](https://cloud.githubusercontent.com/assets/14195653/10727543/593e4802-7be3-11e5-980e-aa000150a55d.png)

**Comment by naticomstar** [comment]
כיוון שלא אופיין עד כה ומעולם לא נלקח בחשבון, יש צורך ב2 שעות עבודה עבור מנגנון החיפוש של אי הילדים

**Comment by nizanmalkit** [comment]
הכוונה היא שכלל לא יופיעו באי הילדים..
עמודי אופניים אינם אמורים להיות בעלי גרסת "אי הילדים".
ומן הסתם לכשלא יהיו כאלו גם לא אמורים לעלות בחיפוש..

**Comment by naticomstar** [comment]
מכיוון שמדובר בהסרת תשובות ולא תיקון לינקים, יש צורך לעדכן את מנגנון החיפוש שוב. נא אישורכם ל4 שעות עבודה
(מדובר בשינוי מנגנון החיפוש לגמרי, כאשר תהיה הפרדה גם לאי הילדים, שבו לא יחזרו תוצאות של מסלולי אופניים, מסלולי אב של אופניים, ומסלולי אב של אי ירוק)

**Comment by nizanmalkit** [comment]
מאושר.
מזכיר שבשיחתנו הוספנו גם את ההתעלמות מעמודי אב (עתידיים) של אי ירוק

**Comment by gadcomstar** [comment]
טופל.
התוצאות היחידות שמופיעות בחיפוש הינם מסלולים המתאימים למילות החיפוש.

**Comment by nizanmalkit** [comment]
תקול !!!
כל החיפוש באתר!!

![image](https://cloud.githubusercontent.com/assets/12142243/10823391/39c3334c-7e64-11e5-8f79-ab0077514568.png)

**Comment by naticomstar** [comment]
תוקן
