### ISSUE TITLE
הסרת כפתור העלאת תמונה מדף הבית 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#18]
בעמוד הבית קיים כפתור להעלאת תמונות אשר מכיל בתוכו את כל רשימת המסלולים 

רשימה זו מייצרת כפילות
קסטים בעמוד שלא טובה לגוגל
![image](https://cloud.githubusercontent.com/assets/14195653/10731781/a7c96b7a-7bff-11e5-9e59-9c2c09cf3a54.png)

בעקבות המלצתה של מיכל אנו רוצים להסיר את הכפתור 
האפשרות להעלאת תמונות קיימת בכל מסלול ותוסר רק מעמוד הבית.

**Comment by naticomstar** [comment]
ידרוש שעת עבודה עקב הסרת תכנים כפולים של האזור הנ"ל (כולל רספונסיבי)

**Comment by shirachen** [comment]
מאושר

**Comment by naticomstar** [comment]
בוצע
