### ISSUE TITLE
עדכון לשונית באי ירוק

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#19]
1.  הלשונית של "הכול" מעודכנת במערכת עם הטייטל הנכון:
   ![image](https://cloud.githubusercontent.com/assets/14195653/10752072/9b37caf2-7c8e-11e5-92aa-0e23d50b5cb3.png)

![image](https://cloud.githubusercontent.com/assets/14195653/10752079/a7bd6bc4-7c8e-11e5-8e5f-235775af8dee.png)
אבל בעמוד עצמו – אין שינוי בכותרת הלשונית: (וניסיתי לשנות גם את הכותרת של עמוד המסלולים [id 22 בתמונה למעלה] – ולא רק של "הכול" – וגם היא לא מתעדכנת)

![image](https://cloud.githubusercontent.com/assets/14195653/10752086/bf868f24-7c8e-11e5-8138-2b134acd7033.png)

**Comment by naticomstar** [comment]
שינוי זה מתבצע בעריכת "מסלולים" ולא "הכול". בכל מקרה מדובר גם בעמוד "מסלולים" של אי ירוק ולא אופניים
(ID=22)

עדכנתי את שם השדה ל
TITLE
בכדי שלא יהיו אי הבנות
![image](https://cloud.githubusercontent.com/assets/13998692/10752871/acd4ca42-7c95-11e5-83d3-87db587a419b.png)

**Comment by shirachen** [comment]
בבקשה תעני לו כך:

מה שענית – שינוי שדה הטייטל – משנה את הנראות של הכותרות באתר עצמו – ואני מתכוון לטקסט שיהיה כתוב רק בלשונית הנפתחת.
הצלחתי לעדכן את זה בצפון:
בחלון זה אין שינוי:

![image](https://cloud.githubusercontent.com/assets/14195653/10757515/35a59bf8-7cb4-11e5-9ae7-a6146b0fa4f5.png)

השינוי רק בלשונית הקידום:
![image](https://cloud.githubusercontent.com/assets/14195653/10757527/4a5b3382-7cb4-11e5-8365-116e967c63f1.png)

וכך זה מוצג, בכותרת הלשונית באתר:
![image](https://cloud.githubusercontent.com/assets/14195653/10757555/7c64ac78-7cb4-11e5-904f-10eb726c8b97.png)

איני מצליח לעשות זאת ב"הכול":
למרות שהגדרתי את הכותרת הרצויה בחלונית הקידום:

![image](https://cloud.githubusercontent.com/assets/14195653/10757583/9f390302-7cb4-11e5-9bf3-953bd187d601.png)

זה לא נשאב לכותרת הלשונית המוצגת באתר, שנשארת "מסלולים":
![image](https://cloud.githubusercontent.com/assets/14195653/10757614/ca813d7c-7cb4-11e5-88f0-8600669b5f32.png)

ניסיתי לשנות זאת גם ב"מסלולים" (22) – וזה גם לא מתעדכן.

אם אני משנה את שדה הטייטל זה משנה לי את התצוגה בסרגל באתר ולא בלשונית של העמוד עצמו – ואת זה איני רוצה.

תודה,
גיא

**Comment by naticomstar** [comment]
כמו שכבר הבהרתי, לא מעדכנים את הכותרת הזאת ב"הכל" אלא ב"מסלולים",
ID=22
![image](https://cloud.githubusercontent.com/assets/13998692/10759406/c716c26e-7cbf-11e5-8288-098847256b9a.png)

![image](https://cloud.githubusercontent.com/assets/13998692/10759409/d15eee0e-7cbf-11e5-9e2f-a862188f139b.png)

![image](https://cloud.githubusercontent.com/assets/13998692/10759536/6e5046fe-7cc0-11e5-9a82-d0412d2ef50e.png)
