### ISSUE TITLE
שגיאה לשונית בדף הבית, לטיפול דחוףףףף

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#2]
![image](https://cloud.githubusercontent.com/assets/14195653/10475930/9cd52dc4-7251-11e5-89ae-c07355282f21.png)

**Comment by OmerComstar** [comment]
טופל

**Comment by shirachen** [comment]
בבקשה עדכנו שהטקסט כאן יהיה h1 
![image](https://cloud.githubusercontent.com/assets/14195653/10726269/50dd41da-7bda-11e5-84e5-017e1fdca29d.png)

**Comment by naticomstar** [comment]
בוצע
