### ISSUE TITLE
מסלולים מומלצים - אלו שקשורים לחיפוש החדש שלנו

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#20]
```
ניסיתי להזין עכשיו מסלולים מומלצים אחרי שנטע אישרה, ואני לא מצליח. כשאני מזין את ה-id של הטיול, זה מגיע לעמוד שגיאה:
```

![image](https://cloud.githubusercontent.com/assets/14195653/10752112/f2ed31d8-7c8e-11e5-9a0f-a2b2e3c987bb.png)

![image](https://cloud.githubusercontent.com/assets/14195653/10752123/01d604f4-7c8f-11e5-85c6-89093b9062cc.png)

**Comment by naticomstar** [comment]
עלה עדכון למערכת הניהול. כמו כן עודכנו דברים נוספים במערכת לחווית שימוש נעימה יותר

**Comment by shirachen** [comment]
אנחנו לא יודעים איפה זה 
אנא שלח צילום מסך

**Comment by naticomstar** [comment]
גיא עודכן
