### ISSUE TITLE
מסלול שלא מוצג באי הילדים כמסלול השבוע

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#21]
למה מסלול השבוע באי ירוק לא מותג כמסלול השבוע באי הילדים

זה כרגע מססלול השבוע באי ירוק 
![image](https://cloud.githubusercontent.com/assets/14195653/10752361/38d6885a-7c91-11e5-86cc-eb91e5bf15aa.png)

ובאי הילדים מוצג המסלול של שבוע שעבר....

**Comment by naticomstar** [comment]
![image](https://cloud.githubusercontent.com/assets/13998692/10759679/63e356a6-7cc1-11e5-851f-6cf692f3f7af.png)

![image](https://cloud.githubusercontent.com/assets/13998692/10759689/6d5771fe-7cc1-11e5-999d-f351dd37b5fe.png)

אני רואה שזה אותו מסלול
