### ISSUE TITLE
איפה אפשר לערוך את הכותרתמשנה הזו? 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#22]
![image](https://cloud.githubusercontent.com/assets/14195653/10752409/a132195a-7c91-11e5-9afc-36c8075448ad.png)

לא ראיתי מקום לזה בניהול

**Comment by naticomstar** [comment]
זה התיאור הקצר של המסלול.

![image](https://cloud.githubusercontent.com/assets/13998692/10753022/a97c621e-7c96-11e5-89b0-9543ce4e4e6e.png)

**Comment by shirachen** [comment]
וגם זה לא רלוונטי.
זה התיאור הקצר לעמוד טיול הרגיל, שנשאב אוטומטית לאי הילדים – כפי שידענו.
אין לי מקום נפרד לאי הילדים בניהול לשלוט בכותרת המשנה הזאת

**Comment by naticomstar** [comment]
נכון, עד היום זה לא אופיין. ידרוש 1.5 שעות פיתוח

**Comment by shirachen** [comment]
מאושר

**Comment by naticomstar** [comment]
בוצע
![image](https://cloud.githubusercontent.com/assets/13998692/10783317/9f68403a-7d5f-11e5-877f-035cd5603b54.png)
