### ISSUE TITLE
קובץ kml

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#23]
שלומות,

שוב בעיה עם הקובץ KML.
אני עדכנתי בו את הנקודות דרך גוגל ארת', והוא נפתח שם בצורה תקינה (מצ"ב הקובץ), אבל בתצוגה באתר זה לא עובר:
כך הקובץ כפי שנפתח בגוגל ארת':

![image](https://cloud.githubusercontent.com/assets/14195653/10757141/8eca9fa6-7cb1-11e5-9a11-5b9c408b5026.png)

כך בתצוגה באתר:
![image](https://cloud.githubusercontent.com/assets/14195653/10757154/a368869e-7cb1-11e5-80e6-73996060483d.png)

**Comment by naticomstar** [comment]
איזה מסלול? אנא שלחי לינק

**Comment by nizanmalkit** [comment]
http://www.eyarok.org.il/trip.aspx?id=2048

**Comment by naticomstar** [comment]
אנא רעננו, אני רואה את המסלול תקין (יש לציין שאני לא רואה את הנתיב עצמו אך יכול להיות שזאת בעיה באיך שהקובץ נשמר דרך גוגל ארת')
![image](https://cloud.githubusercontent.com/assets/13998692/10763987/c944434e-7cd4-11e5-90bc-d6983e773a68.png)

**Comment by shirachen** [comment]
הנקודות נצפות 
השאלה היא למה לא רואים את הנתיב 
בגוגל ארת זה נראה תקין

**Comment by naticomstar** [comment]
הבעיה כנראה בקובץ, שכן גם בגוגל ארת' לא רואים את המסלול. יכול להיות שהמרתם אותו בצורה לא נכונה או שהנתיב לא יכול להיות מוצג בסוג קובץ כזה. נסו להמיר אותו לנתיב מסוג שונה
![image](https://cloud.githubusercontent.com/assets/13998692/10783578/72723f52-7d61-11e5-9f8e-5bdda94c6a71.png)

**Comment by nizanmalkit** [comment]
הבעיה לא בקובץ..
כשאנחנו מציגים אותו בגוגל ארת הוא עם הקו.
ניסינו שוב עכשיו
אם תרצה שוב את הקובץ שאותו אנחנו מעלים תגיד ואשלח לך.

![image](https://cloud.githubusercontent.com/assets/12142243/10788145/206c9ca8-7d7e-11e5-8a39-cdfde87c730e.png)

**Comment by naticomstar** [comment]
אשמח לקובץ המקורי לבדיקה, שכן הורדתי את ה
KML 
מהאתר וטענתי אותו לגוגל ארת'

**Comment by nizanmalkit** [comment]
שולח לך במייל.
יכול להיות שמשהו קורה לו בהעלאה

**Comment by naticomstar** [comment]
עודכן אתמול בערב

**Comment by nizanmalkit** [comment]
החיפוש תקול
![image](https://cloud.githubusercontent.com/assets/12142243/10823336/ecd4f796-7e63-11e5-96d5-4833fe093e51.png)

**Comment by nizanmalkit** [comment]
שלחתי במייל קובץ נוסף, הוא תקין (עם קו מסלול) גם אצלי בגוגל ארתת אבל כשמעלים למערכת הוא מציג את זה בים.
זה מסלול השבוע שלנו אז זה דחוף.

**Comment by naticomstar** [comment]
תוקן
