### ISSUE TITLE
ושוב כפתור החיפוש 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#24]
כשעושים חיפוש "הנזירים " המסלול הזה לא עולה 
למה?
http://www.eyarok.org.il/trip.aspx?id=1740

![image](https://cloud.githubusercontent.com/assets/14195653/10757429/b1aed080-7cb3-11e5-99c5-a6cfa8248364.png)

![image](https://cloud.githubusercontent.com/assets/14195653/10757488/0272b4d2-7cb4-11e5-8cf1-f01a7af346f9.png)

אבל הוא כן עולה בתוצאות חיפוש כשמחפשים - בן שמן
![image](https://cloud.githubusercontent.com/assets/14195653/10757471/ef02dc56-7cb3-11e5-8f71-da125a754a01.png)

**Comment by gadcomstar** [comment]
טופל.
