### ISSUE TITLE
אי ירוק API

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#25]
היי,
אני רוצה להוסיף לאפליקציה את היכולת להוסיף תגובות לאתר..
כרגע ניתן רק לראות את התגובות הקיימות ולהודיע אם מי מהן בעלת אופי לא ראוי
GetComments
SetReportInappropiateComment
אנא תמחרו לי את זה

**Comment by naticomstar** [comment]
מדובר בכ 2 שעות פיתוח

**Comment by nizanmalkit** [comment]
מאושר

**Comment by nizanmalkit** [comment]
אנא העלה את זה ל
http://docs.kakalapi.apiary.io/#comments
תודה

**Comment by naticomstar** [comment]
הועלה לאויר מבחינת API
כמו כן עודכן אתר אי ירוק בתמיכה עבוד שליחת הודעת מייל כאשר מגיבים גם לתגובה דרך האפליקציה
