### ISSUE TITLE
שאיבת אייקון נגיש ואייקון פיקניק כאייקון ראשי 

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#26]
שכאשר במסלול מוגדר אייקון נגיש כאייקון ראשי, הוא לא נשאב בתצוגה:
למשל פארק תמנע (זה קרה גם במסלול נוסף):
http://www.eyarok.org.il/trip.aspx?id=230
שימו לב, זה רלוונטי גם למקרה של אייקון פיקניק! (ואולי עוד..אנא בדקו)
![image](https://cloud.githubusercontent.com/assets/12142243/10787678/4e020e26-7d7b-11e5-9c48-0fce0581e80d.png)

ואחרי השינוי:

![image](https://cloud.githubusercontent.com/assets/12142243/10787694/6b897c72-7d7b-11e5-8a34-ebe20be24124.png)

**Comment by naticomstar** [comment]
עודכן.
