### ISSUE TITLE
אפשרות הסינון של המומלצים (לשם בחירת המסלול) אינה עובדת 

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#27]
לא לפי id של המסלול ולא לפי שם.
צריך לבחור ידנית מסלול מסלול, כלומר לעבור עמוד עמוד, וגם לעשות "שמור" אחרי כל בחירה (כי הוא לא זוכר את הסימון במעבר בין עמודים).

**Comment by naticomstar** [comment]
תוקן
