### ISSUE TITLE
הטמעת פיקסל לעמוד הרשמה אי ירוק

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#28]
נשלח בבוקר מייל עם פיקסל להטמעה. האם הוטמע?

**Comment by nizanmalkit** [comment]
הורדנו את הקמפיין. הפיקסל  עדיין לא סופר!
1.  הכל היה תקין עד ליום שבוצע עדכון להוספת קוביית הרשמה למסלול אופניים ב 21.10
2.  מאז למשך 3ימים וחצי לא היו נרשמים כלל 
3.  לאחר מכן חזרו הנרשמים אך הפיקסל עדיין אינו סופר. 
4.  כרגע הורדנו את הקמפיין כי זה כבר פגע בנו ברמת המחיר להקלקה של פייסבוק (הוא מפרש את זה כחוסר הצלחה של הקמפיין)
5.  מחר נוכל לפנות שוב לפייסבוק כדי לוודא שאין בעיה עם הפיקסל עצמו – אבל לפני זה, אנא וודאו שזו לא בעיה בצד שלכם
6.  זכרו שהכל היה תקין קודם לכן

**Comment by naticomstar** [comment]
הקוד של הפיקסל מופיע בעמוד ההרשמה (לאחר שנרשמו בלבד)
![image](https://cloud.githubusercontent.com/assets/13998692/10868573/5bcd8ebe-809a-11e5-98a6-c3b3b64af964.png)

ניתן לראות אותו ע"י הלינק:
view-source:http://www.eyarok.org.il/contact.aspx?thanks=1
אשר מראה את הקוד של אותו עמוד
