### ISSUE TITLE
שינוי מיקום קבצי ניווט גורם לאי הצגת מפות מסוימות באפליקציה 

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#29]
הנתיב לקובץ משתנה מטיול לטיול.
דוגמא:

לא עובד
TRIP ID -  2048: 
kml url: 
http://www.eyarok.org.il/uploads/files/images/products/24643cd3-320d-436e-bc37-3f3c56855897_Large.kml

עובד
TRIP ID -  1950: 
kml url:
http://www.eyarok.org.il/uploads/files/1950.kml

**Comment by naticomstar** [comment]
יש צורך לנקות קאש של אפליקציה (אם הם שומרים את המידע בתוכה) שכן הפונקציה מפנה למקום נכון
