### ISSUE TITLE
סינון מומלצים - באג מעצבן...

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#30]
בכל פעם שמבצעים סינון הוא מרענן את כל הדף ולכן מקפיץ אותך למעלה גם אם מה שסיננת היה בחלק התחתון של העמוד למשל- מסלולים מומלצים אזור דרום
האם ניתן לעשות עם זה משהו?

**Comment by gadcomstar** [comment]
היי ניצן, 
תוכל בבקשה להסביר על מה מדובר?
האם מדובר במערכת הניהול או באתר עצמו?
האם תוכל לספק את כתובת הדף בו אתה נמצא על מנת שאוכל להתמקד באזור?

תודה והמשך יום נפלא.

**Comment by nizanmalkit** [comment]
כן, סליחה על המחסור בפרטים, זה פשוט המשך טיפול של משהו שמוכר לנתי אבל לא לך..
זה בניהול של אי ירוק

![image](https://cloud.githubusercontent.com/assets/12142243/10867956/b82317ec-8086-11e5-8791-58b35d0b85f1.png)

**Comment by naticomstar** [comment]
עלה עדכון של
TABLECONTROL
שאמור לפתור זאת
