### ISSUE TITLE
כפתור - הייתי שם

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#31]
לאפליקציה (כלומר גם API), לאי ירוק וגם אופניים
בקשה לתמחור-
הוספת כפתור (באפליקציה כבר קיים בעיצוב) בעמודי מסלול ואירוע של שני האתרים שלחיצה עליו תציין שהיית באירוע/בצעת את המסלול הזה..
כמובן עליו להיות רשום ומחובר

בנוסף (תמחורמופרד מהקודם)-
הצגת המסלולים שהגולש ביצע בצורה דומה לכפתור המועדפים שלו

**Comment by naticomstar** [comment]
הוספת כפתור בעמודי מסלולים באי ירוק + באופניים + הוספת כפתור בעמודי אירוע באי ירוק + באופניים + באפליקציה
4.5 שעות פיתוח בתלות עיצוב

הצגת רשימה של "הייתי שם"- בתלות עיצוב ופונקציונליות, צפיה בלבד ומעבר למסלול / אירוע - 2.5 שעות, הסרה מהרשימה- 3.5 שעות
