### ISSUE TITLE
שינוי עמוד מסלול

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#33]
> הוספת "אזור ראשי" מתוך הקטגוריות לפני האזור המשני הקיים כבר.
> הוספת "משך מסלול בקילומטרים"- טווחים לפי dropdown.
> הוספתי שם מסלול מעגלי (כן/לא)
> פירורי לחם - כבר אמור להיות מבוצע (במשימה אחרת)
> הוספת רמת קושי למסלולים (מדובר באתן רמות קושי ולא אחרות עם דרגות / טקסטים שונים)
> בנוסף הוספנו "שטח מיוחד" לחדשות החמות. יש לדאוג שיהיה מקום להוספה בניהול של עמוד (=מסלולים כתבות מגזין ואירועים) ושהתאריך למטה יהיה של אותו יום (יתעדכן אוטומטית ויופיע כל עוד ההחדשה החמה "באויר")- כלומר לא מדובר בתאריך עדכון ההודעה אלא תאריך היום הנוכחי
> הוספנו עוגנים בראש העמוד – כמו באתר האופניים 
> שינינו את הדופ דאון של הורדת קובץ הניווט – שיהיה כמו אתר האופניים הורדה למחשב + שליחת מייל + הכל 
> שינינו את התנהגות האווטברין אנחנו ניפטר ממנו ונשתמש במנגנון כמו של אתר האופניים. שואב ראנדומלית מסלולים תחת אותה קטגוריה
> בנוסף הוספתי בעמוד מסלול ליניקים והפניות למלא מקומות:
- המשך קריאה באתר מסלולי אופניים (טקסט מנוהל עם ברירת מחדל, הזנת לינק מלא בניהול)
- לינק לעמוד האב (טקסט מנוהל עם ברירת מחדל, לינק אוטומטי)
- הטבה למסלול (טקסט מנוהל עם ברירת מחדל, הזנת לינק מלא בניהול)
- הפניה לאי הילדים (טקסט מנוהל עם ברירת מחדל, הזנת לינק מלא בניהול)
- לינק נוסף להפניה כללית (טקסט מנוהל ללא ברירת מחדל, הזנת לינק מלא בניהול)

**Comment by shirachen** [comment]
רק מוסיפה,
![image](https://cloud.githubusercontent.com/assets/14195653/10915567/1046a3fa-8260-11e5-99ea-32b0dfd3aa2a.png)

**Comment by shirachen** [comment]
וגם.
אפשרות בניהול שלכל עמוד תהיה אפשרות להזין טייטל ודסקריפשן שונים וייחודיים (היום לכל עמוד מסלול קיימות גרסאות זהות של תגיות meta title)

לדוגמא לעמוד http://www.eyarok.org.il/trip.aspx?id=1838 קיימת URL נוסף בגרסאות הבאות ולכולם אותו title:
http://www.eyarok.org.il/PathOnMap.aspx?id=1838 עמוד מפה
http://www.eyarok.org.il/TripGallery.aspx?type=1&id=1838 עמוד גלריה
http://www.eyarok.org.il/TripGallery.aspx?type=2&id=1838 גלריה נוספת
http://www.eyarok.org.il/KidsIsland/trip.aspx?id=1838 אי הילדים

**Comment by naticomstar** [comment]
שירה,
נא לפתוח טיקט חדש לדברים ש"רק הוספת" בכדי לא ליצור בלבול ואי הבנות.
השאר בוצע וממתין אצלנו. יש צורך בעיצוב והערכת מחיר לרספונסיבי בכדי שנוכל להעלות לאתר ולא יהיו עיוותים במצב הרספונסיבי.

**Comment by naticomstar** [comment]
בנוסף מערכת הניהול חווה שינוי נוסף, באזור עריכת המסלול, כאשר באם נכנסים דרך אי ירוק רואים אלמנטים שלא יראו באופניים ולהפך

**Comment by shirachen** [comment]
אז לפתוח חדש למה שהוספתי? 
רספונסיבי אעביר בימים הקרובים

**Comment by shirachen** [comment]
נתי עדכן בבקשה מה עם זה?

**Comment by naticomstar** [comment]
בוצע
