### ISSUE TITLE
פירורי לחם 1

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#34]
לחיצה על אזור (למשל צפון) מהפירורים לא שולחת לעמוד הצפון אך עם כותרת של "תוצאות חיפוש" ולא מסלולים בצפון
כמוכן התקציר אינו מופיע

כאשר בעמוד מסלול -גלריה- נוצר שיבוש בתצוגה
http://www.eyarok.org.il/tripgallery.aspx?type=1&id=1950

![image](https://cloud.githubusercontent.com/assets/12142243/10869715/e802d6b2-80bf-11e5-80dc-48eb9955abae.png)

**Comment by naticomstar** [comment]
תוקן פילטר של אזורים בחיפוש + אזור ריק של גלרייה

**Comment by shirachen** [comment]
זה צפוף שם
![image](https://cloud.githubusercontent.com/assets/14195653/10934559/47524f1e-82e9-11e5-828d-74d76d06a5fb.png)

**Comment by shirachen** [comment]
סליחה ככה
![image](https://cloud.githubusercontent.com/assets/14195653/10935420/c87ce00e-82ee-11e5-8dc9-a9fe8a2ddff3.png)

**Comment by naticomstar** [comment]
תיקון בוצע מקומית ויעלה עם העמוד החדש
