### ISSUE TITLE
אייקונים באיכות וחיתוך לא טובים

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#37]
מפוקסלים ומטושטשים
וגם האזוריםימין ותחתון של כל עיגול חתוכים

![image](https://cloud.githubusercontent.com/assets/12142243/10869754/2b3a0c74-80c1-11e5-938f-0b062792e9fe.png)

**Comment by naticomstar** [comment]
כך התמונות הועלו על ידי מנהל התוכן
ראה דוגמא לאייקון
http://www.eyarok.org.il/images/TripIconsImages/49b785d9-ebc6-42c9-aaa3-16c4bd1e8847_small.png

**Comment by nizanmalkit** [comment]
הבנתי, יטופל משמעתית
