### ISSUE TITLE
גלילה אינסופית-קפיצה קדימה אינה פועלת

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#38]
אם אני מזין את הלינק הבא בחלון חדש
http://www.eyarok.org.il/trips.aspx?page=3
הוא לא לוקח אותי לעמוד השלישי, מדוע?

**Comment by naticomstar** [comment]
הוא כן לוקח אותך לעמוד שלישי, שים לב כי התוצאות שונות. על מנת לראות את עמוד 2 ו1, עליך לגלול למעלה. ההנחיות של הגלילה הזאת אומרות כי גוגל (וגם הצופה) אמור לראות רק את התוצאות הרלוונטיות ולא את כולם בשביל למנוע כפילות תוכן. אם תגלול למעלה תראה כי יתווספו תוצאות מהעמודים הקודמים לפני התוצאות שעלו בפעם הראשונה.

**Comment by nizanmalkit** [comment]
הבנתי. אני מניח שמה שבלבל אותי זה שמופיע ההדר
