### ISSUE TITLE
למקרה שלא ראיתם  -נעלמו מגוגל דפי המסלולים האיזוריים באתר האופניים

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#39]
התיאור נמצא בגיט של אופניים והוא הכי דחוף
לאחר התיקון עלינו להגיש את העמודים מחדש לגוגל

לדעתי זה נובע משינויים שערכתם בכלל לאי ירוק ..

**Comment by shirachen** [comment]
היי שירה וניצן,

בבדיקה שעשינו זה נראה שעדיין לא תוקן - הקישור לקנוניקל השגוי עדיין מופיע בדפי האיזורים (צפון, דרום, מרכז).

**Comment by naticomstar** [comment]
תוקן היום בבוקר, נמסר מידע במייל
