### ISSUE TITLE
תמחור עמוד מסלול ועמוד אב

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#4]
![image](https://cloud.githubusercontent.com/assets/14195653/10563710/a07acbd8-759d-11e5-9c83-a9fd2fd7e736.png)

![image](https://cloud.githubusercontent.com/assets/14195653/10563712/ad5a77f4-759d-11e5-8df4-fb7da8121e97.png)

**Comment by naticomstar** [comment]
נשלח תמחור מפורט במייל
