### ISSUE TITLE
מסלולי אב אי ירוק

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#40]
הוספת עמוד מסלול אב. העמוד יכיל:
1.      הסבר קצר (על בסיס עורך טקסט CK)
2.      מסלולים הקשורים לאותו מסלול אב.
3.      הוספנו בעמוד האב מפת גוגל עם נקודות של המסלולים עליה כולל פופ אפ של טקסט ותמונה - יהיה צורך שתיצרו קובץ KML ייחודי לכל מסלול האב ועורך התוכן יעלה אותו בניהול במסלולי האב של אי ירוק
4.      אני רוצה שתהיה לי בניהול אפשרות הזנת תקציר ייחודי נוסף למסלולים שישאבו לעמוד האב + לתמונה – שיהיו בשליטת עורך התוכן כמו באתר האופניים - שאיבת תקציר מ"תיאור קצר (עמוד אב)"
5.      הטמעת תמונת QR
6.      טמפרטורה ומזג אויר (ייקבע לפי הוספת נקודת ציון למסלול האב)
7.      פירורי לחם.

**Comment by shirachen** [comment]
היי נתי, איפה זה עומד? 
אני רוצה לנסות לעשות שינוי עם המפה בעמוד הזה

**Comment by naticomstar** [comment]
עמוד מוכן מקומית, יעלה לאחר התאמה לרספונסיבי

**Comment by shirachen** [comment]
נשלח אליכם עיצוב למובייל
עדכנו בלוז
תודה

**Comment by naticomstar** [comment]
בוצע
