### ISSUE TITLE
שינוי עמוד מפות מסלול

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#41]
1.      בטאב מפות ירוכזו כל המפות עם כפתורים לכל סוגי המפות כמו באתר האופניים:
   a.      הוספת מפת PDF
   b.      הוספת מפת תצ"א
   c.      הוספת מפת גבהים
   d.      הוספת טקסט של "מפת סימון שבילים" + טקסט מנוהל
2.      הוספת פירורי לחם
3.      הוספת QR
4.      הוספת "משך המסלול" מתחת למזג האויר

**Comment by naticomstar** [comment]
שינוי בוצע מקומית, יעלה לאחר אישור + עדכון למצב רספונסיבי כיוון שהעמוד לא ייראה טוב כלל בטלפונים כרגע

**Comment by shirachen** [comment]
כנ"ל

**Comment by naticomstar** [comment]
בוצע
