### ISSUE TITLE
שינוי עמוד גלריית תמונות

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#42]
1.      גלריית התמונות – תהיה מעכשיו עמוד אחד. תמונות גולשים + קק"ל ביחד אותו איפון כמו באתר האופנים:
   1.      ביטול "תמונה ראשונה גדולה" 
   2.      הוספת משך מסלול מתחת למזג האויר .. איפה יש בתמונות מזג אוויר? צודק, צריך להוסיף גם מזג אויר בנוסף למשך המסלול
2.      הוספת QR
3.      הוספת "תמונת גולש" בתמונות הגולשים
4.      שינוי מיקומי אייקונים (עריכה, דיווח, הסרה)
5.      הוספת אייקונים (עריכה, דיווח, הסרה) כאשר התמונה פתוחה בפנסי

**Comment by naticomstar** [comment]
היי,
עד כה לא היתה התייחסות עבור אייקון של תמונה אשר הגיעה מאי הילדים. בהמשך לשיחתי עם שירה ורעות הוחלט שהאייקון יוקטן, יעוגל, ויעלה לפינה השמאלית העליונה של תמונות המשתמשים.

**Comment by naticomstar** [comment]
בוצע מקומית, כרגע לא עולה עד אשר תתבצע התאמה רספונסיבית

**Comment by shirachen** [comment]
נשלח אליכם יצוב מובייל 
עדכנו בלוז

**Comment by naticomstar** [comment]
בוצע
