### ISSUE TITLE
עמוד תגית 

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#43]
a.      הסבר קצר על התגית (על בסיס עורך טקסט CK) אולי לאוו דווקא ck וניצור תבנית קבועה.
b.      מסלולים המשויכים לאותה תגית.
2.           הוספת לינקביליות לתגיות בעמוד המסלול, אשר מפנה לעמוד התגית
3.           עדכון תיוגים קיימים במסד הנתונים

**Comment by gadcomstar** [comment]
המשימה בוצעה במקומי וטרם הועלתה.
ממתין לאישור העיצוב הריספונסיבי על מנת להתאים את הדברים הנדרשים באזור זה.

**Comment by shirachen** [comment]
נשלח אליכם עיצוב מובייל
עדכנו בלוז

**Comment by naticomstar** [comment]
בוצע
