### ISSUE TITLE
השינויים בעמוד החיפוש במובייל

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#45]
היי לא נראה כאילו החלתתם את העיצובים ששלחתי לכם במובייל

בדקתי גם באייפון וגם באנדרואיד

אנא טיפולכם 
שירה

**Comment by naticomstar** [comment]
היי שירה, איזה עיצובים שלחת? מתי?

**Comment by shirachen** [comment]
היי נתי במייל ששלחתי את הדסקופ שלחתי גם את המובייל
אם לא תמצא דבר איתי אשלח לך שוב...

**Comment by naticomstar** [comment]
היי שירה,

אנא שלחי שוב, איני מבין על מה את מדברת....

**Comment by nizanmalkit** [comment]
שירה לא היתה אתמול.
אנסה למצוא את זה ולשלוח לך (אני מגיע רק בצהריים)

**Comment by nizanmalkit** [comment]
שלחתי לך במייל

**Comment by naticomstar** [comment]
נראה תקין לפי מה שנשלח במייל

**Comment by nizanmalkit** [comment]
ראית את מה שהקפתי בעיגול?
זה לא נראה כמו בעיצוב...

![image](https://cloud.githubusercontent.com/assets/12142243/11241970/9f37c730-8e07-11e5-9272-b4f2bca2ecea.png)

אני לא יודע לגבי המסלולים פופולריים אם אמורים להופיע אחד מתחת לשני או לא אבל שני הדברים הנוספים לא נראים כמו בעיצוב..

![image](https://cloud.githubusercontent.com/assets/12142243/11242069/17eb8202-8e08-11e5-8e25-0d02dbb23107.png)

**Comment by naticomstar** [comment]
חלק עליון סודר. בנוגע למסלולים המומלצים לא קיבלנו עיצוב עד כמה שאני זוכר.
