### ISSUE TITLE
חדשות חמות גם באפליקציה 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#46]
בהמשלך למיילים מאושר 

היי ניצן

נוכל במערכת הניהול להוסיף בעת יצירת הודעה חדשה (או עריכתה) "אפליקציה / אתר" מה שיפריד את ההודעות הרלוונטיות עבור האפליקציה.

מבחינת הקוד של האפליקציה נצטרך לברור את ההודעות אשר שייכות רק לאפליקציה בלבד

כל הנ"ל לעניות דעתי יוכל להתבצע בתוך 3 שעות עבודה.

OK.
מאושר.

אך מכיוון שהאפליקציה באויר ומותקנת אצל אנשים,

תשאיר בבקשה גם את הפונקציה הנוכחית באויר, במקביל לחדשה שתוסיף.. כך שעד שהם לא ישתמשו בחדשה הקודמת עדיין תהיה פעילה (ואני מניח שמן הסתם תציג את כל ההודעות).
או
שתכתוב אותה כך שעדין תהיה פעילה כך שאם הם לא מציינים שהם מציגים רק את ההודעות של "האפליקציה" יוצגו כולן..
או
רעיון אחר..

היי ניצן

נא להוסיף את הנ"ל בגיט הא ונטפל בהתאם לפי סדרי העדיפויות.

בנוסף, שם מחזור:
אי ירוק - קק"ל - הוספת אבחנה להודעות חמות אפליקציה / אתר - 08/11/2015

**Comment by naticomstar** [comment]
בוצע והועלה למערכת. בפרטים במייל שנשלח
