### ISSUE TITLE
טקסט מתחת לפוטר בעמוד הבית 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#47]
היי אני צריכה לעדכן את הטקסט שם לטקסט הזה:
![image](https://cloud.githubusercontent.com/assets/14195653/11021054/311c9742-863e-11e5-8015-107471db9146.png)

במקום מה שיש עכשיו....
זה:
![image](https://cloud.githubusercontent.com/assets/14195653/11021056/459abc76-863e-11e5-9350-6d7618a74057.png)

**Comment by naticomstar** [comment]
בוצע, יחוייב במחזור הכללי עבור משימות קטנות של חצי שעת עבודה
