### ISSUE TITLE
סיור הקולי  לא יושב טוב בעמוד מסלול

### ISSUE THREAD

**Issue by kazantip151** [nizanmalkit/eyarok.org.il#48]
יש בעיה עם פופאפ של סיור הקולי בעמוד מסלול. הוא סוגר שאר האלמנטים בעמוד. צריך להוריד אותו קצת למתה.

![sound_popup](https://cloud.githubusercontent.com/assets/2787866/11059161/b2a168c0-87a0-11e5-85e2-f715d78790b6.jpg)

**Comment by gadcomstar** [comment]
בעיה זו אינה קיימת בעיצוב החדש.
ברגע שהגרסה החדשה תועלה - תוכלו לראות זאת.
