### ISSUE TITLE
סרגל מידע נוסף (מידע, מפה, גלרייה, תצוגת 360)  עולה על פירורי לחם

### ISSUE THREAD

**Issue by kazantip151** [nizanmalkit/eyarok.org.il#49]
היי.אם יש כותרת ארוכה בעמוד מסלול היא נשברת לשתי שורות ואז היא דוחפת סרגל מידע על פירורי לחם.

![breadcrumbs](https://cloud.githubusercontent.com/assets/2787866/11065131/46fca254-87ca-11e5-8c8c-daf40b3a8f2e.JPG)

**Comment by gadcomstar** [comment]
בעיה זו אינה קיימת בעיצוב החדש.
ברגע שהגרסה החדשה תועלה - תוכלו לראות זאת.
