### ISSUE TITLE
התאמת אתר הראי לאי ירוק לטובת בדיקת האבטחה

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#5]
היי,
לאחר שיצרנו את העותק של אתר אי ירוק - כדי שגוגל לא יחשוב שיש כאן כפילות תכנים ויוריד לנו את הניקוד, אנא:
1.  יש להוסיף קובץ ROBOTS (או לעדכנו אם קיים) כך שלא יאפשר סריקה (disallow)
2.  להוסיף בכל דפי האתר NO INDEX

**Comment by naticomstar** [comment]
נא אשרו שעת עבודה

**Comment by nizanmalkit** [comment]
מאושר.
נא לבצע ביום ראשון בבוקר.
1 לנובמבר

**Comment by nizanmalkit** [comment]
קבענו לביצוע היום, עדכנו כשבוצע

**Comment by naticomstar** [comment]
נוסף קובץ
ROBOTS
ונוסף
noindex,nofollow
בעמודי המאסטר הראשיים (אי ירוק, אי הילדים, אופניים)
ממליץ לכם למחוק את התיקיות של מיני האתרים (כביש 6 שבועות ועוד) כיוון שהם לא רלוונטיים מבחינת האבטחה ויש בהם גם פיקסלים, אינדקסים למיניהם וכדומה
