### ISSUE TITLE
אם לא הוזן בניהול שלא יפיע...

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#50]
![image](https://cloud.githubusercontent.com/assets/14195653/11168206/e692a590-8b8d-11e5-982b-e9103cd84bac.png)

**Comment by naticomstar** [comment]
כשיש לך "כן" ו"לא" בלבד, אין לך אם לא הוזן... ניתן להוסיף אפשרות של "האם להציג מסלול מעגלי כן לא" בעריכת המסלול, ידרוש שעת פיתוח, נא אישורך

**Comment by nizanmalkit** [comment]
הכוונה היא שאם מופיע "לא" הוא לא יופיע כלל בעמוד..
האם זו שעת עבודה?

**Comment by naticomstar** [comment]
חצי שעת עבודה (במשימה המרוכזת) נא אישורך

**Comment by nizanmalkit** [comment]
מאושר

# 

nizan malkit
052.4004441

**Comment by naticomstar** [comment]
בוצע
