### ISSUE TITLE
ובפוטר למטה

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#51]
הטלפון נשבר שורה לא טוב.

וגם המסלולים הנוספים למטה לא יושבים טוב

![image](https://cloud.githubusercontent.com/assets/14195653/11168239/cda26538-8b8e-11e5-80e6-4e6ac8d262f9.png)

**Comment by naticomstar** [comment]
עודכן.
הורדתי שורה במספר הטלפון כדי שלא תהיה שורה ארוכה מדי
