### ISSUE TITLE
עמוד מסלול שלא אמור להיות מוצג..

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#52]
הטיול  (איי-די 10) בעיקרון בכלל לא אמור להיות באוויר. במערכת הניהול כתוב שהוא אינו מוצג

![image](https://cloud.githubusercontent.com/assets/12142243/11179152/1aab8b7c-8c5a-11e5-9cec-1dd31a40b7ee.png)

הבעיה זה שהגולשים כן חשופים אליו – ואתמול מישהו העלה אליו תמונת גולש.
http://www.eyarok.org.il/tripgallery.aspx?id=10

וגם, לא מופיעה עבורו תמונת ה"הדר"..

**Comment by naticomstar** [comment]
נבדק ונמצא תקין. שימו לב שהמערכת תיתן גישה לעמוד למי שיש לו הרשאות כניסה למערכת הניהול (וזה נשמר בזכרון המטמון של הדפדפן).
אם תיכנסו לעמוד זה במצב אינקוגניטו, תראו כי העמוד אינו קיים.
התמונה הזאת יכולה להיות כנסיון של מישהו מאצלכם להעלאה. האם למחוק אותה ממסד הנתונים?

**Comment by nizanmalkit** [comment]
זו תמונה שהועלתה אתמול, ולא על ידי מישהו מטעמנו (ככל הידוע לנו..)
אם למחוק אותה או לא אני עוד לא יודע אבל בכל מקרה, אנחנו יכולים למחוק בעצמנו :)

**Comment by naticomstar** [comment]
אנא דבר איתי טלפונית כשאתה מגיע למשרד, אני חושב שישנה בעיה התנהגותית כאן בנוגע להעלאת תמונות

**Comment by nizanmalkit** [comment]
אנא התקשר אלי.. אני מתקשר מידי פעם אבל אין תשובה מ102

**Comment by naticomstar** [comment]
כנ"ל... :)
זמין בחמש וחצי?

**Comment by nizanmalkit** [comment]
היי זה שוב קרה... הטיול לא מוצג אבל מישהו הוסיף תמונה

טיול ברכבי שטח לרמת סירין וליבנאל בגליל התחתון המזרחי
http://www.eyarok.org.il/tripgallery.aspx?type=2&id=16

![image](https://cloud.githubusercontent.com/assets/12142243/11322743/a8a26156-9102-11e5-8c65-de99072a453c.png)

**Comment by naticomstar** [comment]
התמונה הועלתה מאי הילדים
![image](https://cloud.githubusercontent.com/assets/13998692/11323757/c20c7e34-9124-11e5-9b70-84de9f84fb20.png)

רואים לפי האייקון הירוק.
עדכנתי כעת באי הילדים חסימה לעמוד זה אם הטיול לא מוצג (הפניה לעמוד הבית כיוון שאין עמוד "עמוד זה אינו קיים")
