### ISSUE TITLE
תצוגת מז"א באפליקציה

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#55]
היי,
האם עשינו שינוי כלשהו שמסביר את זה שבאפליקציה לא מופיע יותר מזג האויר במסלולים?

![image](https://cloud.githubusercontent.com/assets/12142243/11240541/6178184c-8dfc-11e5-8cd9-07da7d3b0e53.png)

**Comment by naticomstar** [comment]
היי,
לא. מזג האויר מתקבל ישירות לאפליקציה לא דרכנו, בעזרת נקודות ציון בלבד.
אני רואה שנקודות הציון כן מגיעות אל האפליקציה שכן היא אומרת לך מה המרחק שלך מהמסלול.
לעניות דעתי מדובר בעומס על השרת שבודק את מזג האויר, לא בתלות האפליקציה או ה
API

**Comment by nizanmalkit** [comment]
באפליקציה זה נמשך כנראה כבר כמה ימים..
אתה מושך את המז"א ממקור אחר?

**Comment by naticomstar** [comment]
אנחנו לא מושכים את מזג האויר. פעם משכנו אותו ואז אחרי כמה זמן קיבלנו דיליי (מקווה שאתה זוכר) לאחר מכן העברנו את הנושא לצד לקוח (דפדפן או אפליקציה) והם עצמם פונים למי שמחזיר את מזג האויר, בתלות בנקודות ציון.

**Comment by nizanmalkit** [comment]
אם כך, אז למי הם פונים..?

**Comment by naticomstar** [comment]
בעיקרון לתשובה 100% נכונה תצטרך לשאול אותם, אבל אנחנו בזמנו העברנו את בקשת מזג האויר מהכתובת
http://api.openweathermap.org
במקום יאהו (שהיה בעבר)
יש סיכוי מאוד סביר שגם הם משתמשים בזה, כיוון שזה היה הדיבור בזמנו, שאנו נשתמש באותה קריאה שהם השתמשו בה

**Comment by nizanmalkit** [comment]
במילה הם התכוונתי לגולשים של האתר - זו היתה כוונתך בצד לקוח.. לא?
כלומר באתר (לא אפליקציה) מאיפה הגולשים מושכים את המז"א?
מכאן? 
http://api.openweathermap.org

**Comment by naticomstar** [comment]
אכן, מהכתובת הזאת.
