### ISSUE TITLE
קישור לא נכון במסלול

### ISSUE THREAD

**Issue by kazantip151** [nizanmalkit/eyarok.org.il#56]
היי.
קישור לא נכון של סינגל הרצל ביער בן שמן. בלחיצה מובילה לסינגל שמשית.

![ercel](https://cloud.githubusercontent.com/assets/2787866/11266232/bfd18aae-8eab-11e5-89c4-ae7ba129abf0.JPG)

![shemshit](https://cloud.githubusercontent.com/assets/2787866/11266234/c3f3cc14-8eab-11e5-92ca-d7f058fab6d8.JPG)

**Comment by naticomstar** [comment]
תוקן
טכנית לא העביר לשביל אופניים שמשית אלא פשוט לעמוד הבית של אופניים

**Comment by nizanmalkit** [comment]
מה הכוונה? האם יתכן שיש עוד כאלה?

**Comment by naticomstar** [comment]
היו. הכל תוקן באותה שורת קוד.
