### ISSUE TITLE
בעיה בחיפוש

### ISSUE THREAD

**Issue by kazantip151** [nizanmalkit/eyarok.org.il#57]
היי.
חיפשתי את המילה ע'רבאווי.
המילה מופיעה כאן: http://www.eyarok.org.il/trip.aspx?id=271
אך החיפוש לא נותן לי את התוצאה. הוא כותב שאין נתונים תואמים...
ניסיתי גם בלי אפוסטרוף. זה גם לא מביא תוצאות.

**Comment by naticomstar** [comment]
תוקן!

**Comment by nizanmalkit** [comment]
בכל ענייני החיפוש - אנא בדוק בשתי תיבות החיפוש.....
ראה מה קורה כשמחפשים בעליונה - הוא מוסיף גרש לגרש הקיים..

![image](https://cloud.githubusercontent.com/assets/12142243/11271601/b7a52aba-8ecf-11e5-8495-e173ca980867.png)

**Comment by naticomstar** [comment]
תוקן. יש לנקות קאש ספציפית בעמוד
trips.aspx
