### ISSUE TITLE
בעיה ביצירת תגובה באפליקציה

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#58]
מדובל נמסר לי ש

הפונקציה http://api.eyarok.org.il/Service1.svc/Comment/SetComment
אינה שולחת בכלל בקשה לשרת, ואני מקבל את השגיאה הבאה:

דוגמא לשליחה:
http://api.eyarok.org.il/Service1.svc/Comment/SetComment?ItemType=1&Id=1939&name="ziv"&email="ziv@dooble.co.il"&comment="very nice trip"&CommentParent=4759

דוגמא לתשובה:
POST http://api.eyarok.org.il/Service1.svc/Comment/SetComment 405 (Method Not Allowed)

**Comment by naticomstar** [comment]
היי, כעת תקין.
הבעיה לא נוצרה מהפונקציה ב
API
אלא במתודה אשר היתה שולחת מייל לכותב התגובה הראשונה על כך שהגיבו לו על התגובה.
כעת תקין.
