### ISSUE TITLE
עמוד הרשמה לניוזלטר חדש עבור אי ירוק 

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#6]
העמוד החדש צריך להחליף את הישן הזה: 
http://www.eyarok.org.il/contact.aspx?c=footer27048

התווסף בעיצובים האלו 
1.  עמוד חיווי תודה - אחרי שהוא עולה, נרצה שהעמוד יחזור לדף הבית אחרי כמה שניות  
2.  הרשמה גם לאתר האופניים.

תודה

**Comment by shirachen** [comment]
בוקר טוב.
ייתכן והדף לא עובד?
ניסתי להירשם הבוקר ללא הצלחה.
לא נותן לי להגיע לדף תודה
![image](https://cloud.githubusercontent.com/assets/14195653/10751413/ae4cc4f4-7c88-11e5-93e9-e6417b91edf0.png)

**Comment by shirachen** [comment]
ועוד דבר מסתבר שמ 22.10 אין נרשמים חדשים.
זה אומר שהתקלה הזו באוייר הרבה זמן!

**Comment by gadcomstar** [comment]
טופל.

**Comment by shirachen** [comment]
למה אין לעמוד תודה 
url
משלו? 
האם יש שם את הםיקסל שהעברתי לכם? 
איך נמדוד נרשמים??

**Comment by naticomstar** [comment]
תעבירי לי בבקשה את הפיקסל ואחזיר לך בתמורה
URL
של ה"תודה"

**Comment by shirachen** [comment]
רותם תשלח מייל מחר בבוקר

**Comment by gadcomstar** [comment]
טופל.
contact.aspx?thanks=1
