### ISSUE TITLE
מפת אתר של אי ירוק חסרה..

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#60]
ראינו שהמפת אתר של אי ירוק שהיתה בכתובת הזו: 
http://www.eyarok.org.il/sitemap.xml
הוסרה מהאתר. 
זה מקשה על גוגל לסרוק את האתר. 
האם תוכלו לבדוק מה קרה למפת האתר, ולדאוג שתחזור למקומה?

**Comment by naticomstar** [comment]
תוקן, היתה בעיה ב
WEBCONFIG
שלא ידע לקרוא קבצי
XML
תוך כדי

**Comment by nizanmalkit** [comment]
היי, שים לב,
דפי המסלולים של אתר האופניים ודפי האיזורים צפון/מרכז/דרום לא מופיעים בה, 
ויש כמה מהדפים שמופיעים בה עם שגיאה, למשל זה: 
http://www.eyarok.org.il//bike/trips.aspx
שמופיע עם שני // לפני ה-bike.

**Comment by naticomstar** [comment]
כיוון שהדפים האלה חדשים ולא דינאמייל (כמו למשל עמודי מסלולים, אירועים וכדומה) יש לעדכן את מפת האתר בכדי שתוכל לקרוא אותם כמו שצריך
נא אישורכם ל1 שעות פיתוח בנושא זה.
