### ISSUE TITLE
 בעיה עם התיוגים שהוזנו וגם עם התפריט הצדדי בכתבות מגזין 

### ISSUE THREAD

**Issue by kazantip151** [nizanmalkit/eyarok.org.il#61]
בכתבות מגזין באתר לא מוצגים התיוגים שהוזנו ולא מוצג כל התפריט הצדדי, גם אם הוזנו בו נתונים:
http://www.eyarok.org.il/article.aspx?id=1

![magazin](https://cloud.githubusercontent.com/assets/2787866/11340891/bfc7e9da-9208-11e5-9249-4946942cfadc.jpg)

**Comment by naticomstar** [comment]
בעת העדכון של עמוד הטיול החדש לא נלקח בחשבון עמודי מגזין.
כרגע העתקתי את עמוד הטיול החדש לכתבות המגזין, עם שינויים קלים בכדי שכתבות המגזין יעבדו תקין, הפעם ללא חיוב.
