### ISSUE TITLE
אין אופציה לבחור במערכת הניהול מספר ק"מ

### ISSUE THREAD

**Issue by kazantip151** [nizanmalkit/eyarok.org.il#62]
באורך המסלול בק"מ, האופציות אמורות להיות:
![1](https://cloud.githubusercontent.com/assets/2787866/11341116/b15f8050-9209-11e5-989f-d497bd335a0b.png)

אבל בפועל, כשהזנו 2 ק"מ זה נשאב כך:
![2](https://cloud.githubusercontent.com/assets/2787866/11341126/ba88a440-9209-11e5-8f3c-817230ccf87c.jpg)

בכלל אין אופציה לבחור במערכת הניהול, רק להכניס מספר ק"מ:
![3](https://cloud.githubusercontent.com/assets/2787866/11341133/c39e41ac-9209-11e5-8ce5-7963472bfd23.png)

**Comment by naticomstar** [comment]
זהו לא באג. יש לציין תחת "אורך הטיול בק"מ" את מספר הקילומטרים של המסלול. המערכת תחשב את דרגת האורך המתאימה בעת חיפוש / הצגה.

**Comment by kazantip151** [comment]
אבל הכנסנו 2 ק"מ, וזה כתב 1-10 ק"מ, במקום 1-2 ק"מ. זה הבאג מבחינתנו...

**Comment by naticomstar** [comment]
הבנתי. תוקן
