### ISSUE TITLE
שינוי תגיות target="_blank לטובת האפליקציה

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/eyarok.org.il#63]
יש בכל מיני דפים פנימיים, שמגיעים מה-api
תגיות עם href="link.to.web" target="_blank"
רצוי להחליף את הטארגט ל "_system"
הערך מזוהה ע״י האפליקציה. ופותח כתובת בדפדפן שמוגדר כברירת מחדל באייפון\אנדרואיד
תודה

**Comment by naticomstar** [comment]
לא הבנתי כלל, אנא תן דוגמאות

**Comment by nizanmalkit** [comment]
בקשתי,
ובינתיים..
האם אתה יודע על מקום ב-API שבו אתה משתמש בטארגט=בלאנק?

**Comment by naticomstar** [comment]
אנחנו לא מחזירים טרגטים (אלא אם כן מדובר בתוך תוכן טקסטואלי שאין לנו עליו שליטה)
