### ISSUE TITLE
הסתרת חדשות חמות מהאתר

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/eyarok.org.il#8]
כשאתם מגיעים לזה - עדכנו אותי אשלח מייל בנושא
חשוב לקבל את המייל לפני תחילת העבודה!

**Comment by naticomstar** [comment]
אנא שלחי את המייל, ובנוסף אנא אשרי את 2.5 השעות המקוריות בכדי שנוכל לבצע (עדיין לא אושר)

**Comment by nizanmalkit** [comment]
נשלח האישור במייל

**Comment by naticomstar** [comment]
בוצע
